name = "alice_project_euler_rocher"
version = "0.1.1-dev"
description = "Problems for Alice / Project Euler"

authors = ["Francesc Rocher"]
maintainers = ["Francesc Rocher <francesc.rocher@gmail.com>"]
maintainers-logins = ["rocher"]

[build-switches]
"*".ada_version = ["-gnat2022", "-gnatX", "-gnatW8"]

[[depends-on]]
euler_tools = "^1.1.1"
project_euler = ">=0.1.0-dev"
[[pins]]
project_euler = { path='../..' }
