name = "alice_project_euler_rocher"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Francesc Rocher"]
maintainers = ["Francesc Rocher <francesc.rocher@gmail.com>"]
maintainers-logins = ["rocher"]

executables = ["alice_project_euler_rocher"]
[[depends-on]]
euler_tools = "^1.1.1"
[[depends-on]]
alice_project_euler = "~0.1.0-dev"
[[pins]]
alice_project_euler = { path='../..' }
